// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import GeometricAnimationController from "./geometric_animation_controller"
application.register("geometric-animation", GeometricAnimationController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import TagifyController from "./tagify_controller"
application.register("tagify", TagifyController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import TypingActionController from "./typing_action_controller"
application.register("typing-action", TypingActionController)
